name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull and run Docker image
      run: |
        # Pull the image from Docker Hub
        docker pull ${{ secrets.DOCKER_USERNAME }}/my-python-app
        
        # Run the container on localhost on port 5000
        docker run -d --name my_local_container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-python-app

    - name: Show running Docker containers
      run: docker ps -a
